### PR TITLE
Support password policy error response

### LINKED ISSUE #109: signup method of Auth0 Java Client is throwing ClassCastException when specified password strength does not meet password complexity rules
signup method of Auth0 Java Client is throwing ClassCastException when specified password strength does not meet password complexity rules.

On signup - if the specified password value violates the configured password complexity rules for the related connection - the Java client is throwing  ClassCastException  ( attempt to cast Map into a String ),

### PR DESCRIPTION
**Pull request by lbalmaceda**
Will fix #109

### CODE REVIEW

**Comment by PudiPudi** [comment]
Not sure where to ask; but any idea when this fix will be available through maven?
version 1.5.0 imports the old version without this fix

**Comment by lbalmaceda** [comment]
@PudiPudi that's because `1.5.0` is from December and this fix from February. I'll try to make a release tomorrow.

**Comment by PudiPudi** [comment]
@lbalmaceda thank you, didn't looked at the dates, my mistake

**Comment by lbalmaceda** [comment]
@PudiPudi released on `1.5.1`.

**Pull request merged**
