### PR TITLE
Add refresh token configuration object to client

### PR DESCRIPTION
**Pull request by JakeUskoski**
### Changes

Proposed solution to issue #318 

This PR includes a new object for managing the configuration of refresh tokens associated with a client, as well as the addition of the class (`RefreshToken`) as an instance variable on the `Client` class. The design is a 1-to-1 mapping of the refresh token configuration as defined in the [Auth0 Management API](https://auth0.com/docs/api/management/v2#!/Clients/get_clients).

I did not include enums for the `rotation_type` or `expiration_type` fields in the refresh token configuration like what was done in https://github.com/auth0/auth0.net/pull/451/ as the rest of the Java API relies on strings for all areas that would otherwise use enums.

This change is meant to allow for the use of documented API functionality which is currently unavailable in the SDK.

### References

* Relates to #318 
* Considered https://github.com/auth0/auth0.net/pull/451/ when planning the design

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

- [x] This change adds test coverage
- [x] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [x] All existing and new tests complete without errors

### CODE REVIEW

**Comment by JakeUskoski** [comment]
Live testing completed, all looks good 🙂

**Comment by jimmyjames** [comment]
Thanks @JakeUskoski! Change looks good. Mind rebasing your changes on latest master? Then I can approve and merge. This will be included in version `1.26.0`, which we plan on releasing the week of November 30.

**Review by jimmyjames — APPROVED** [review]

**Comment by cihati** [comment]
@jimmyjames when will 1.26.0 be released? Very much looking forward to using this = )

**Comment by jimmyjames** [comment]
@cihati it is planned for this week. Once #325 is approved and merged we can get a release out. Thanks!

**Comment by jimmyjames** [comment]
1.26.0 has been released. Thanks again!

**Pull request merged**
