### PR TITLE
[SDK-3742] support Authorization Code + PKCE

### PR DESCRIPTION
**Pull request by jimmyjames**
Adds support for Authorization Code Flow with PKCE.

* Adds a new method to the `AuthorizeUrlBuilder` to add a `code_challenge` parameter when making the `/authorize` request
* Adds a new method to `AuthAPI` to include the `code_verifier` on the request to `/oauth/token` to exchange the code for the tokens

The implementation of the `code_verifier` and `code_challenge` is left to the user - when we make use of this in `mvc-commons` that library will generate the verifier and its challenge.

### CODE REVIEW

**Comment by poovamraj** [comment]
This PR looks great, I just had one thought on it.

Should we provide secure defaults rather than allowing the user to create the challenge? In our mobile SDKs which does PKCE by default, we provide sane secure defaults.

**Review by poovamraj — COMMENTED** [review]
This PR looks great, I just had one thought on it.

Should we provide secure defaults rather than allowing the user to create the challenge? In our mobile SDKs which does PKCE by default, we provide sane secure defaults.

**Comment by jimmyjames** [comment]
> Should we provide secure defaults rather than allowing the user to create the challenge? In our mobile SDKs which does PKCE by default, we provide sane secure defaults.

Can you expand on that a bit, what you mean specifically?

Originally we planned to provide the ability to generate the verifier and challenge ([discovery doc](https://oktawiki.atlassian.net/wiki/spaces/DXSDK/pages/2540967790/auth0-java+vNext#PKCE-Support)), but upon review decided that mvc-commons would handle the crypto stuff. But not sure if that's what you're referring to.

**Comment by poovamraj** [comment]
Makes sense that we will make it easier to use in mvc-commons and customizable in auth0-java 👍

**Review by poovamraj — APPROVED** [review]

**Pull request merged**
