### PR TITLE
ManagementAPI: Allow customizing HTTP client

### PR DESCRIPTION
**Pull request by kdubb**
### Changes
This simple change allows an `OkHttpClient.Builer` to be passed into the ManagementAPI’s constructor allowing clients of the ManagmentAPI to customize the HTTP client that is used internally.

A constructor was __added__. No binary/source compatibility should be affected.

An example usage...
```java
OkHttpClient.Builder clientBuilder =
  new OkHttpClient.Builder()
    .addInterceptor(MyRateLimitingInterceptor())
ManagementAPI api = new ManagementAPI(myDomain, myApiToken, clientBuilder);
```

### Use Case
We are using the ManagementAPI to handle fine-grained permissions with multi-tenancy by adding an “API per account”  (per the Auth0 recommendation).  This requires us to interact with the Management API regularly. The API has a very low rate limit and we were hitting it regularly.  OkHttp’s `Interceptor`s were a perfect solution but the current code offers no ability to access or customize the HTTP client. This commit allows us to pass in a client builder with a rate limiting interceptor and resolve our issues with rate limiting.

### References

Please include relevant links supporting this change such as a:

- [Auth0 Rate Limits, which includes requests to respect them](https://auth0.com/docs/policies/rate-limits)

### Testing

Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If this library has unit and/or integration testing, tests should be added for new functionality and existing tests should complete without errors. 

- [ ] ~This change adds test coverage~ N/A
- [X] This change has been tested on the latest version of the platform/language or why not

### Checklist

- [X] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
- [X] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
- [X] All existing and new tests complete without errors

### CODE REVIEW

**Comment by kdubb** [comment]
For anybody wondering how to implement the rate limiting interceptor, here is a simple one based on Google Guava's `RateLimiter`... 
```java
class HttpRateLimitInterceptor implements Interceptor {

  private RateLimiter rateLimiter;

  HttpRateLimitInterceptor(Double requestsPerSecond) {
      this(RateLimiter.create(requestsPerSecond))
  }

  HttpRateLimitInterceptor(RateLimiter rateLimiter) {
    this.rateLimiter = rateLimiter;
  }

  @Override
  Response intercept(Interceptor.Chain chain) {
    rateLimiter.acquire(1);
    return chain.proceed(chain.request());
  }

}
```

**Comment by roioteromorales** [comment]
Can we add something similar for the AuthenticationController builder?
`    return AuthenticationController.newBuilder(domain, clientId, clientSecret)
        **.withOkHttpClient(new OkHttpClient.Builder().proxy(proxyTest).build())**
        .withJwkProvider(jwkProvider)
        .build();`

This would solve the proxy for servers which are lock down want to authenticate and they need a proxy to do any external call.

**Comment by stevehobbsdev** [comment]
@kdubb Thanks for raising this and apologies that you haven't had a response yet. We're doing some internal discovery in this area and we will have something to share with you soon.

In the meantime, could you update this branch with the latest code from master? I don't have the permission to do it myself.

**Comment by lbalmaceda** [comment]
I think we can all benefit from a Rate Limit interceptor implementation, but the solution _cannot expose_ third-party APIs in the method signatures.

We can still achieve such a feature internally knowing the API limits explained [here](https://auth0.com/docs/policies/rate-limits). I'm not sure if there should be a need for customization, but if we require that, we can expose a method to configure it in the `HttpOptions` class that is being introduced in #266.

I'd close this PR because it exposes the OkHttp classes, and suggest we add an issue to track this feature request. We're not tracking this internally @stevehobbsdev.

**Comment by lbalmaceda** [comment]
I'm going to close this PR and track it internally, for reference Steve, this is currently under `SDK-1702`.

**Pull request closed without merging**
